version: '3'
services: 
  tests:
    build: 
     context: .
     dockerfile: Dockerfile.dev
  weatherapplication:
    build: 
     context: .
     dockerfile: Dockerfile2.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app