# use an existing docker image as a base
FROM golang:1.11.1 as tester
#Installing additional tools for the container
WORKDIR '/go/src/app'
COPY . .
RUN go get -d -v github.com/tools/godep
RUN go test -c -o /out/app.test
RUN go build -o /out/runme
CMD ["/out/app.test"]

#CMD COMMANDS------------------------------------------

#FROM alpine as release
#COPY --from=builtapp /out /out
#WORKDIR '/go/src/app'
#CMD ["app"]

# commands: docker run -p 8080:8080 -v "//c/Users/Public/Weather_app_development:/go/src/app" ae75d2ef6e30